apiVersion: v1
kind: Service
metadata:
  name: apireticula
  labels:
    api: apireticula
    rol: webservice
    nivel: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    api: apireticula
    rol: webservice
    nivel: backend