apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    api: mysql
    rol: bd
    nivel: backend
spec:
  type: NodePort
  ports:
  - port: 3306
  selector:
    api: mysql
    rol: bd
    nivel: backend