apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-apireticula
  labels:
    api: apireticula
    zone: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"